port: {{ default(global.clash.http_port, "7890") }}
socks-port: {{ default(global.clash.socks_port, "7891") }}
allow-lan: {{ default(global.clash.allow_lan, "true") }}
mode: rule
log-level: {{ default(global.clash.log_level, "info") }}
external-controller: :9090

{% if default(request.adg, "true") == "true" or exists("request.adg.port") %}
dns:
  enable: true
  ipv6: true
  listen: 127.0.0.1:{{ default(request.adg.port, "5450") }}
  enhanced-mode: redir-host
  default-nameserver:
    - 119.29.29.29
    - 119.28.28.28
    - 1.0.0.1
    - 208.67.222.222
    - 1.2.4.8
  nameserver:
    - 223.5.5.5 # 阿里DNS
    - 180.76.76.76 # 百度DNS
    - 119.29.29.29 # 腾讯DNS
    - 117.50.11.11 # ONE DNS拦截版 恶意网站拦截、广告过滤
    - 117.50.10.10 # ONE DNS纯净版 直接返回其真实的响应结果
    - 114.114.114.114 # 114DNS
  fallback:
    - tls://8.8.8.8:853
    - tls://8.8.4.4:853
    - https://149.112.112.112:5053/dns-query
    - https://9.9.9.9:5053/dns-query
    - https://dns.quad9.net:5053/dns-query
{% endif %}
